<?php

$protectedByDefault = env('API_REQUIRE_AUTH', false);

return [
    'title' => 'Factu Lite API',
    'version' => '1.1',
    'base_url' => env('APP_URL', 'http://localhost:8080'),
    'groups' => [
        [
            'name' => 'General',
            'description' => 'Health check and status consultation.',
            'endpoints' => [
                [
                    'name' => 'Ping',
                    'method' => 'GET',
                    'path' => '/api/ping',
                    'description' => 'Quick endpoint to verify that the API is up.',
                    'requires_auth' => false,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                    ],
                ],
                [
                    'name' => 'Modo de Emision API',
                    'method' => 'GET',
                    'path' => '/api/mode',
                    'description' => 'Returns active environment for API emission: demo, production or ose.',
                    'requires_auth' => false,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'mode' => 'demo',
                        'soap_type_id' => '01',
                        'soap_send_id' => '01',
                    ],
                ],
                [
                    'name' => 'Status de Comprobante',
                    'method' => 'POST',
                    'path' => '/api/documents/status',
                    'description' => 'Returns current status and download links for a voucher.',
                    'requires_auth' => false,
                    'payload' => [
                        'external_id' => '84f2c5ea-9b73-4ce8-a315-8b383f56ee0f',
                        'serie_number' => 'F001-123',
                    ],
                    'response' => [
                        'success' => true,
                        'data' => [
                            'number' => 'F001-123',
                            'filename' => '20111111111-01-F001-123',
                            'external_id' => '84f2c5ea-9b73-4ce8-a315-8b383f56ee0f',
                            'status_id' => '05',
                            'status' => 'ACEPTADO',
                            'qr' => 'base64...',
                        ],
                        'links' => [
                            'xml' => 'https://host/downloads/document/xml/{external_id}',
                            'pdf' => 'https://host/downloads/document/pdf/{external_id}',
                            'cdr' => 'https://host/downloads/document/cdr/{external_id}',
                        ],
                    ],
                ],
            ],
        ],
        [
            'name' => 'Autenticacion',
            'description' => 'Login API, validacion de token y cierre de sesion.',
            'endpoints' => [
                [
                    'name' => 'Login API',
                    'method' => 'POST',
                    'path' => '/api/auth/login',
                    'description' => 'Valida credenciales y entrega un token Bearer nuevo.',
                    'requires_auth' => false,
                    'payload' => [
                        'email' => 'admin@empresa.com',
                        'password' => '123456',
                    ],
                    'response' => [
                        'success' => true,
                        'message' => 'Login API exitoso.',
                        'token_type' => 'Bearer',
                        'token' => 'TOKEN_GENERADO',
                        'data' => [
                            'id' => 1,
                            'name' => 'Administrador Demo',
                            'email' => 'admin@empresa.com',
                            'type' => 'admin',
                            'locked' => false,
                        ],
                    ],
                ],
                [
                    'name' => 'Verificar Token',
                    'method' => 'GET',
                    'path' => '/api/auth/verify',
                    'description' => 'Verifica si el token enviado es valido y retorna usuario autenticado.',
                    'requires_auth' => true,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'message' => 'Token valido.',
                        'data' => [
                            'id' => 1,
                            'name' => 'Administrador Demo',
                            'email' => 'admin@empresa.com',
                            'type' => 'admin',
                            'locked' => false,
                        ],
                    ],
                ],
                [
                    'name' => 'Perfil Actual',
                    'method' => 'GET',
                    'path' => '/api/auth/me',
                    'description' => 'Devuelve el usuario de la sesion API actual.',
                    'requires_auth' => true,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'message' => 'Token valido.',
                        'data' => [
                            'id' => 1,
                            'name' => 'Administrador Demo',
                            'email' => 'admin@empresa.com',
                            'type' => 'admin',
                            'locked' => false,
                        ],
                    ],
                ],
                [
                    'name' => 'Logout API',
                    'method' => 'POST',
                    'path' => '/api/auth/logout',
                    'description' => 'Revoca el token activo del usuario autenticado.',
                    'requires_auth' => true,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'message' => 'Token revocado.',
                    ],
                ],
            ],
        ],
        [
            'name' => 'Configuracion Empresa',
            'description' => 'Endpoints para sincronizar datos de empresa, logo y certificado desde un sistema externo (modo monoempresa).',
            'endpoints' => [
                [
                    'name' => 'Catalogos de Configuracion',
                    'method' => 'GET',
                    'path' => '/api/company/tables',
                    'description' => 'Devuelve catalogos basicos para configurar entorno SOAP.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'data' => [
                            'soap_types' => [
                                ['id' => '01', 'description' => 'SUNAT - Beta'],
                                ['id' => '02', 'description' => 'SUNAT - Produccion'],
                            ],
                            'soap_sends' => [
                                ['id' => '01', 'description' => 'Sunat'],
                                ['id' => '02', 'description' => 'OSE'],
                            ],
                        ],
                    ],
                ],
                [
                    'name' => 'Obtener Empresa Activa',
                    'method' => 'GET',
                    'path' => '/api/company/record',
                    'description' => 'Retorna la configuracion de empresa usada para enviar CPE a SUNAT.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'data' => [
                            'id' => 1,
                            'number' => '20111111111',
                            'name' => 'EMPRESA DEMO SAC',
                            'trade_name' => 'EMPRESA DEMO',
                            'soap_send_id' => '01',
                            'soap_type_id' => '02',
                            'soap_username' => 'MODDATOS',
                            'soap_password' => 'SECRETO',
                            'soap_url' => null,
                            'detraction_account' => null,
                            'operation_amazonia' => false,
                            'certificate' => 'certificate_20111111111.pem',
                            'has_certificate' => true,
                            'logo' => 'logo_20111111111.png',
                            'logo_url' => 'https://host/storage/uploads/logos/logo_20111111111.png',
                            'api_mode' => 'production',
                        ],
                    ],
                ],
                [
                    'name' => 'Crear/Actualizar Empresa',
                    'method' => 'POST',
                    'path' => '/api/company',
                    'description' => 'Crea o actualiza la empresa activa. Si ya existe empresa y no envias id, actualiza la activa.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'id' => 1,
                        'identity_document_type_id' => '6',
                        'number' => '20111111111',
                        'name' => 'EMPRESA DEMO SAC',
                        'trade_name' => 'EMPRESA DEMO',
                        'soap_send_id' => '01',
                        'soap_type_id' => '02',
                        'soap_username' => 'MODDATOS',
                        'soap_password' => 'SECRETO',
                        'soap_url' => null,
                        'detraction_account' => null,
                        'operation_amazonia' => false,
                    ],
                    'response' => [
                        'success' => true,
                        'message' => 'Empresa guardada correctamente.',
                        'data' => [
                            'id' => 1,
                            'number' => '20111111111',
                            'soap_type_id' => '02',
                            'api_mode' => 'production',
                        ],
                    ],
                ],
                [
                    'name' => 'Subir Logo de Empresa',
                    'method' => 'POST',
                    'path' => '/api/company/logo',
                    'description' => 'Carga logo principal de la empresa. Enviar en multipart/form-data.',
                    'requires_auth' => $protectedByDefault,
                    'content_type' => 'multipart/form-data',
                    'payload' => [
                        'file' => '@/path/logo.png',
                    ],
                    'response' => [
                        'success' => true,
                        'message' => 'Logo cargado correctamente.',
                        'data' => [
                            'logo' => 'logo_20111111111.png',
                            'logo_url' => 'https://host/storage/uploads/logos/logo_20111111111.png',
                        ],
                    ],
                ],
                [
                    'name' => 'Subir Certificado Digital',
                    'method' => 'POST',
                    'path' => '/api/company/certificate',
                    'description' => 'Sube certificado .pfx/.p12 y lo convierte a .pem para firma local. Enviar en multipart/form-data.',
                    'requires_auth' => $protectedByDefault,
                    'content_type' => 'multipart/form-data',
                    'payload' => [
                        'file' => '@/path/certificado.pfx',
                        'password' => 'clave-certificado',
                    ],
                    'response' => [
                        'success' => true,
                        'message' => 'Certificado cargado correctamente.',
                        'data' => [
                            'certificate' => 'certificate_20111111111.pem',
                            'has_certificate' => true,
                        ],
                    ],
                ],
                [
                    'name' => 'Eliminar Certificado Digital',
                    'method' => 'DELETE',
                    'path' => '/api/company/certificate',
                    'description' => 'Elimina certificado activo de la empresa.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'message' => 'Certificado eliminado correctamente.',
                        'data' => [
                            'certificate' => null,
                            'has_certificate' => false,
                        ],
                    ],
                ],
            ],
        ],
        [
            'name' => 'Comprobantes',
            'description' => 'Voucher issuance and processing.',
            'endpoints' => [
                [
                    'name' => 'Emitir Comprobante',
                    'method' => 'POST',
                    'path' => '/api/documents',
                    'description' => 'Creates and signs a voucher. This endpoint uses the legacy payload format (Spanish keys). Demo/Prod mode is taken from company SOAP Tipo.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'serie_documento' => 'F001',
                        'numero_documento' => '#',
                        'fecha_de_emision' => '2026-02-18',
                        'hora_de_emision' => '10:00:00',
                        'codigo_tipo_documento' => '01',
                        'codigo_tipo_operacion' => '0101',
                        'fecha_de_vencimiento' => '2026-02-18',
                        'codigo_tipo_moneda' => 'PEN',
                        'factor_tipo_de_cambio' => 1,
                        'datos_del_cliente_o_receptor' => [
                            'codigo_tipo_documento_identidad' => '6',
                            'numero_documento' => '20111111111',
                            'apellidos_y_nombres_o_razon_social' => 'CLIENTE DEMO SAC',
                            'nombre_comercial' => 'CLIENTE DEMO SAC',
                            'codigo_pais' => 'PE',
                            'ubigeo' => '010101',
                            'direccion' => 'Direccion demo',
                            'correo_electronico' => 'cliente.demo@example.com',
                            'telefono' => '999999999',
                        ],
                        'totales' => [
                            'total_anticipos' => 0,
                            'total_descuentos' => 0,
                            'total_cargos' => 0,
                            'total_exportacion' => 0,
                            'total_operaciones_gratuitas' => 0,
                            'total_operaciones_gravadas' => 100,
                            'total_operaciones_inafectas' => 0,
                            'total_operaciones_exoneradas' => 0,
                            'total_igv' => 18,
                            'total_igv_operaciones_gratuitas' => 0,
                            'total_base_isc' => 0,
                            'total_isc' => 0,
                            'total_base_otros_impuestos' => 0,
                            'total_otros_impuestos' => 0,
                            'total_impuestos_bolsa_plastica' => 0,
                            'total_impuestos' => 18,
                            'total_valor' => 100,
                            'subtotal_venta' => 118,
                            'total_venta' => 118,
                            'total_pendiente_pago' => 0,
                        ],
                        'items' => [
                            [
                                'codigo_interno' => 'PRD-001',
                                'descripcion' => 'PRODUCTO DEMO LITE 1',
                                'codigo_tipo_item' => '01',
                                'codigo_producto_sunat' => '',
                                'unidad_de_medida' => 'NIU',
                                'cantidad' => 1,
                                'valor_unitario' => 100,
                                'codigo_tipo_precio' => '01',
                                'precio_unitario' => 118,
                                'codigo_tipo_afectacion_igv' => '10',
                                'total_base_igv' => 100,
                                'porcentaje_igv' => 18,
                                'total_igv' => 18,
                                'total_impuestos' => 18,
                                'total_valor_item' => 100,
                                'total_item' => 118,
                            ],
                        ],
                        'acciones' => [
                            'enviar_email' => false,
                            'formato_pdf' => 'a4',
                        ],
                        'pagos' => [
                            [
                                'fecha_de_emision' => '2026-02-18',
                                'codigo_metodo_pago' => '01',
                                'codigo_destino_pago' => 'cash',
                                'monto' => 118,
                            ],
                        ],
                    ],
                    'response' => [
                        'success' => true,
                        'data' => [
                            'number' => 'F001-123',
                            'filename' => '20111111111-01-F001-123',
                            'external_id' => '84f2c5ea-9b73-4ce8-a315-8b383f56ee0f',
                            'state_type_id' => '01',
                            'state_type_description' => 'Registrado',
                            'hash' => 'a1b2c3...',
                            'qr' => 'base64...',
                        ],
                        'links' => [
                            'xml' => 'https://host/downloads/document/xml/{external_id}',
                            'pdf' => 'https://host/downloads/document/pdf/{external_id}',
                            'cdr' => 'https://host/downloads/document/cdr/{external_id}',
                        ],
                        'response' => [
                            'code' => '0',
                            'description' => 'La factura ha sido aceptada',
                        ],
                    ],
                ],
                [
                    'name' => 'Emitir Comprobante en Servidor',
                    'method' => 'POST',
                    'path' => '/api/documents_server',
                    'description' => 'Stores voucher and generated files from a remote billing server.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'external_id' => 'server-external-id',
                        'document_type_id' => '01',
                        'series' => 'F001',
                        'number' => 200,
                        'query' => true,
                    ],
                    'response' => [
                        'success' => true,
                    ],
                ],
                [
                    'name' => 'Listar Comprobantes',
                    'method' => 'GET',
                    'path' => '/api/documents/lists',
                    'description' => 'Returns latest vouchers.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'data' => [
                            [
                                'id' => 1,
                                'number' => 'F001-123',
                                'external_id' => '84f2c5ea-9b73-4ce8-a315-8b383f56ee0f',
                                'state_type_id' => '05',
                                'state_type_description' => 'Aceptado',
                            ],
                        ],
                    ],
                ],
                [
                    'name' => 'Consultar Documento en Servidor',
                    'method' => 'GET',
                    'path' => '/api/document_check_server/{external_id}',
                    'description' => 'Returns status from server-side stored document.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'state_type_id' => '05',
                        'file_cdr' => 'base64...',
                    ],
                ],
                [
                    'name' => 'Reenviar Comprobante',
                    'method' => 'POST',
                    'path' => '/api/documents/send',
                    'description' => 'Resends a previously created document to SUNAT.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'external_id' => '84f2c5ea-9b73-4ce8-a315-8b383f56ee0f',
                    ],
                    'response' => [
                        'success' => true,
                        'data' => [
                            'number' => 'F001-123',
                            'external_id' => '84f2c5ea-9b73-4ce8-a315-8b383f56ee0f',
                            'state_type_id' => '05',
                            'state_type_description' => 'ACEPTADO',
                        ],
                        'links' => [
                            'cdr' => 'https://host/downloads/document/cdr/{external_id}',
                        ],
                    ],
                ],
            ],
        ],
        [
            'name' => 'Resumenes y Anulaciones',
            'description' => 'Daily summary and voided documents.',
            'endpoints' => [
                [
                    'name' => 'Crear Resumen Diario',
                    'method' => 'POST',
                    'path' => '/api/summaries',
                    'description' => 'Creates summary for multiple vouchers.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'external_id' => 'sum-20260217-0001',
                        'date_of_reference' => '2026-02-16',
                        'date_of_issue' => '2026-02-17',
                        'documents' => [
                            [
                                'document_type_id' => '03',
                                'series' => 'B001',
                                'number' => 125,
                                'customer_doc_type' => '1',
                                'customer_doc_number' => '44556677',
                                'total' => 20,
                            ],
                        ],
                    ],
                    'response' => [
                        'success' => true,
                        'data' => [
                            'external_id' => 'sum-20260217-0001',
                            'ticket' => '1234567890123',
                        ],
                    ],
                ],
                [
                    'name' => 'Estado de Resumen',
                    'method' => 'POST',
                    'path' => '/api/summaries/status',
                    'description' => 'Checks summary status by external_id or ticket.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'ticket' => '1234567890123',
                    ],
                    'response' => [
                        'success' => true,
                        'data' => [
                            'filename' => '20111111111-RC-20260217-1',
                            'external_id' => 'sum-20260217-0001',
                        ],
                        'links' => [
                            'xml' => 'https://host/downloads/summary/xml/{external_id}',
                            'cdr' => 'https://host/downloads/summary/cdr/{external_id}',
                        ],
                    ],
                ],
                [
                    'name' => 'Crear Comunicacion de Baja',
                    'method' => 'POST',
                    'path' => '/api/voided',
                    'description' => 'Creates voided communication for vouchers.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'external_id' => 'void-20260217-0001',
                        'date_of_reference' => '2026-02-16',
                        'date_of_issue' => '2026-02-17',
                        'documents' => [
                            [
                                'document_type_id' => '01',
                                'series' => 'F001',
                                'number' => 123,
                                'description' => 'ERROR EN MONTO',
                            ],
                        ],
                    ],
                    'response' => [
                        'success' => true,
                        'data' => [
                            'external_id' => 'void-20260217-0001',
                            'ticket' => '9876543210987',
                        ],
                    ],
                ],
                [
                    'name' => 'Estado de Comunicacion de Baja',
                    'method' => 'POST',
                    'path' => '/api/voided/status',
                    'description' => 'Checks voided communication status.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'ticket' => '9876543210987',
                    ],
                    'response' => [
                        'success' => true,
                        'data' => [
                            'filename' => '20111111111-RA-20260217-1',
                            'external_id' => 'void-20260217-0001',
                        ],
                        'links' => [
                            'xml' => 'https://host/downloads/voided/xml/{external_id}',
                            'cdr' => 'https://host/downloads/voided/cdr/{external_id}',
                        ],
                    ],
                ],
            ],
        ],
        [
            'name' => 'Clientes',
            'description' => 'Customer and supplier maintenance.',
            'endpoints' => [
                [
                    'name' => 'Listar Clientes/Proveedores',
                    'method' => 'GET',
                    'path' => '/api/persons/{type}/records?column=name&value=CLIENTE&per_page=20',
                    'description' => 'type can be customers or suppliers.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'data' => [
                            [
                                'id' => 1,
                                'type' => 'customers',
                                'number' => '20111111111',
                                'name' => 'CLIENTE API',
                                'document_type' => 'RUC',
                            ],
                        ],
                        'meta' => [
                            'current_page' => 1,
                            'last_page' => 1,
                            'per_page' => 20,
                            'total' => 1,
                        ],
                    ],
                ],
                [
                    'name' => 'Obtener Cliente/Proveedor',
                    'method' => 'GET',
                    'path' => '/api/persons/record/{person}',
                    'description' => 'Returns one customer or supplier record.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'data' => [
                            'id' => 1,
                            'type' => 'customers',
                            'number' => '20111111111',
                            'name' => 'CLIENTE API',
                            'identity_document_type_id' => '6',
                            'country_id' => 'PE',
                        ],
                    ],
                ],
                [
                    'name' => 'Crear/Actualizar Cliente',
                    'method' => 'POST',
                    'path' => '/api/persons',
                    'description' => 'If id is sent, updates existing record.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'type' => 'customers',
                        'number' => '20111111111',
                        'name' => 'CLIENTE API',
                        'identity_document_type_id' => '6',
                        'country_id' => 'PE',
                        'address' => 'AV. DEMO 123',
                        'email' => 'cliente@demo.com',
                    ],
                    'response' => [
                        'success' => true,
                        'message' => 'Registro creado con exito',
                        'id' => 1,
                        'data' => [
                            'id' => 1,
                            'type' => 'customers',
                            'number' => '20111111111',
                            'name' => 'CLIENTE API',
                        ],
                    ],
                ],
                [
                    'name' => 'Eliminar Cliente/Proveedor',
                    'method' => 'DELETE',
                    'path' => '/api/persons/{person}',
                    'description' => 'Deletes person record by id.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'message' => 'Registro eliminado con exito',
                    ],
                ],
            ],
        ],
        [
            'name' => 'Productos',
            'description' => 'Product maintenance endpoints.',
            'endpoints' => [
                [
                    'name' => 'Listar Productos',
                    'method' => 'GET',
                    'path' => '/api/items/records?column=description&value=PROD&per_page=20&type=PRODUCTS',
                    'description' => 'Use type=PRODUCTS or type=SERVICES.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'data' => [
                            [
                                'id' => 1,
                                'description' => 'PRODUCTO API',
                                'unit_type_id' => 'NIU',
                                'currency_type_id' => 'PEN',
                                'sale_unit_price' => 100,
                            ],
                        ],
                        'meta' => [
                            'current_page' => 1,
                            'last_page' => 1,
                            'per_page' => 20,
                            'total' => 1,
                        ],
                    ],
                ],
                [
                    'name' => 'Obtener Producto',
                    'method' => 'GET',
                    'path' => '/api/items/record/{item}',
                    'description' => 'Returns one product.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'data' => [
                            'id' => 1,
                            'description' => 'PRODUCTO API',
                            'item_type_id' => '01',
                            'unit_type_id' => 'NIU',
                            'sale_unit_price' => 100,
                            'has_igv' => true,
                        ],
                    ],
                ],
                [
                    'name' => 'Crear/Actualizar Producto',
                    'method' => 'POST',
                    'path' => '/api/items',
                    'description' => 'If id is sent, updates existing product.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => [
                        'description' => 'PRODUCTO API',
                        'unit_type_id' => 'NIU',
                        'currency_type_id' => 'PEN',
                        'sale_unit_price' => 100,
                        'purchase_unit_price' => 90,
                        'sale_affectation_igv_type_id' => '10',
                        'purchase_affectation_igv_type_id' => '10',
                        'stock' => 100,
                        'stock_min' => 5,
                    ],
                    'response' => [
                        'success' => true,
                        'message' => 'Producto registrado con exito',
                        'id' => 1,
                        'data' => [
                            'id' => 1,
                            'description' => 'PRODUCTO API',
                            'sale_unit_price' => 100,
                            'stock' => 100,
                        ],
                    ],
                ],
                [
                    'name' => 'Eliminar Producto',
                    'method' => 'DELETE',
                    'path' => '/api/items/{item}',
                    'description' => 'Deletes product by id.',
                    'requires_auth' => $protectedByDefault,
                    'payload' => null,
                    'response' => [
                        'success' => true,
                        'message' => 'Producto eliminado con exito',
                    ],
                ],
            ],
        ],
        [
            'name' => 'Descargas',
            'description' => 'Endpoints publicos para descargar archivos de comprobantes por external_id.',
            'endpoints' => [
                [
                    'name' => 'Descargar PDF de Comprobante',
                    'method' => 'GET',
                    'path' => '/downloads/document/pdf/{external_id}',
                    'description' => 'Descarga el PDF generado del comprobante.',
                    'requires_auth' => false,
                    'payload' => null,
                    'response' => [
                        'file' => 'application/pdf',
                        'status' => 200,
                    ],
                ],
                [
                    'name' => 'Descargar XML de Comprobante',
                    'method' => 'GET',
                    'path' => '/downloads/document/xml/{external_id}',
                    'description' => 'Descarga el XML firmado del comprobante.',
                    'requires_auth' => false,
                    'payload' => null,
                    'response' => [
                        'file' => 'application/xml',
                        'status' => 200,
                    ],
                ],
                [
                    'name' => 'Descargar CDR de Comprobante',
                    'method' => 'GET',
                    'path' => '/downloads/document/cdr/{external_id}',
                    'description' => 'Descarga la constancia CDR del comprobante.',
                    'requires_auth' => false,
                    'payload' => null,
                    'response' => [
                        'file' => 'application/xml',
                        'status' => 200,
                    ],
                ],
            ],
        ],
    ],
];
