server {
    listen 80;
    index index.php index.html;
    server_name kamary.xplain.pe;
    root /var/www/html/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;

        # --- SSE support ---
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        # CORS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
        add_header Access-Control-Allow-Headers 'Origin, X-Requested-With, Content-Type, Accept, Authorization';
        add_header Cache-Control 'no-cache';
    }

    location /storage/images/ {
        alias /var/www/html/storage/app/images/;
        access_log off;
        expires max;
    }

    location ~ \.php$ {
        fastcgi_pass app:9020;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
